import './nav.js';
import './promo-slider.js';
import './programs-slider.js';
import './news-slider.js';
import './reviews-slider.js';
import './form-select.js';
import './form-validate.js';
import './modal.js';
import './modal-validate.js';
